version: '3'

tasks:
  generate:
    desc: Generate files necessary for build.
    cmds:
      - go generate ./...
    sources:
      - '**/*.go'

  build:
    desc: Build the bouncer executable.
    deps:
      - generate
    cmds:
      - go build -o bouncer main.go
    sources:
      - '**/*.go'
    generates:
      - bouncer

  run:
    desc: Run bouncer in debug mode using configs in private/. Set CONFIG to use a different directory.
    deps:
      - build
    cmds:
      - ./bouncer -config {{.CONFIG | default "private/"}} -debug
